
'use strict';var _createClass=(function(){function defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if('value'in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor);}}return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor;};})();function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError('Cannot call a class as a function');}}
var $=(function(){function $(query){_classCallCheck(this,$);this._els={};if(typeof query=='string'){this._els=$.toArray(document.querySelectorAll(query));}else if(Array.isArray(query)){this._els=query;}else{this._els=$.toArray(query);if(this._els.length==0){this._els=[query];}}}
_createClass($,[{key:'on',value:function on(eventName,callback,attributes){var _this=this;this._els.forEach(function(el){return el.addEventListener(eventName,function(event){callback.bind(_this,attributes,event)();});});return this;}},{key:'attr',value:function attr(attributeName,attributeValue){if(!attributeValue){if(this._els[0].getAttribute(attributeName)==='undefined'){return this._els[0][attributeName];}
return this._els[0].getAttribute(attributeName);}else{this._els[0].setAttribute(attributeName,attributeValue);return this;}}},{key:'val',value:function val(value){if(value==null){return this.attr('value')||this._els[0].value;}else{if(this.attr('value')){this.attr('value',value);}else{this._els[0].value=value;}
return this;}}},{key:'nextEl',value:function nextEl(){return new $(this._els.map(function(el){return el.nextElementSibling;}));}},{key:'previousEl',value:function previousEl(){return new $(this._els.map(function(el){return el.previousElementSibling;}));}},{key:'text',value:function text(value){if(value==null){return this._els[0].innerText||this._els[0].textContent;}else{if(this._els[0].innerText){this._els[0].innerText=value;}else if(this._els[0].textContent){this._els[0].textContent=value;}
return this;}}},{key:'html',value:function html(value){if(value==null){return this._els[0].innerHTML;}else{this._els[0].innerHTML=value;return this;}}},{key:'addClass',value:function addClass(className){this._els.forEach(function(el){if(el.className.search(className)==-1){el.className+=' '+className;}});return this;}},{key:'removeClass',value:function removeClass(className){this._els.forEach(function(el){el.className=el.className.replace(RegExp('\\s?'+className,'g'),'');});return this;}},{key:'hasClass',value:function hasClass(className){return this._els[0].className.search(className)!=-1;}},{key:'_hasSelector',value:function _hasSelector(query){var parent=new $(this.parent()._els[0]);var els=parent.find(query);for(var i=0;i<els._els.length;i++){if(els._els[i]==this._els[0]){return true;}}
return false;}},{key:'parent',value:function parent(query){var parent=[];if(query==null){parent=this._els.map(function(el){return el.parentElement;});}else{this._els.map(function(el){var currentParent=new $(el);while(currentParent._els[0]!=document.body&&!currentParent._hasSelector(query)){currentParent=currentParent.parent();}
if(currentParent._els[0]!=document.body&&currentParent._hasSelector(query)){currentParent._els.forEach(function(el){return parent.push(el);});}});}
return new $(parent);}},{key:'children',value:function children(){var children=[];this._els.forEach(function(el){children=children.concat($.toArray(el.children));});return new $(children);}},{key:'show',value:function show(){this._els.forEach(function(el){return el.style.display='block';});return this;}},{key:'hide',value:function hide(){this._els.forEach(function(el){return el.style.display='none';});return this;}},{key:'clearOn',value:function clearOn(){this._els.forEach(function(el){return el.style.visibility='hidden';});return this;}},{key:'clearOff',value:function clearOff(){this._els.forEach(function(el){return el.style.visibility='visible';});return this;}},{key:'style',value:function style(object){var _this2=this;var _loop=function(key){_this2._els.forEach(function(el){return el.style[key]=object[key];});};for(var key in object){_loop(key);}}},{key:'find',value:function find(query){var findEl=this._els.map(function(el){return $.toArray(el.querySelectorAll(query));}).filter(function(el){return el.length!=0?true:false;});var result=[];findEl.forEach(function(array){array.forEach(function(el){result.push(el);});});return new $(result);}},{key:'filter',value:function filter(func){return new $(this._els.filter(function(el,idx){el=new $(el);return func(el,idx);}));}},{key:'el',value:function el(index){return new $(this._els[index]);}},{key:'each',value:function each(func){this._els.forEach(function(el,idx){return func(new $(el),idx);});return this;}},{key:'blur',value:function blur(){this._els.forEach(function(el){return el.blur();});return this;}},{key:'focus',value:function focus(){this._els.forEach(function(el){return el.focus();});return this;}},{key:'appendChild',value:function appendChild(){var _this3=this;for(var _len=arguments.length,elements=Array(_len),_key=0;_key<_len;_key++){elements[_key]=arguments[_key];}
elements.forEach(function(el){return _this3._els[0].appendChild(el._els[0]);});return this;}},{key:'length',get:function get(){return this._els.length;}}],[{key:'new',value:function _new(nameEl,attributes){var newEl=new $(document.createElement(nameEl));for(var key in attributes){newEl.attr(key,attributes[key]);}
return newEl;}},{key:'toArray',value:function toArray(obj){return Array.prototype.slice.call(obj);}}]);return $;})();